{% set version = "1.0.1" %}

package:
  name: ioos_tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ioos_tools/ioos_tools-{{ version }}.tar.gz
  sha256: 99ca893ac0f300582703051f464da9072f90f17de2a280cf4bc04420a0c03a02

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - beautifulsoup4
    - folium
    - iris
    - matplotlib
    - netcdf4
    - numpy
    - oceans
    - owslib
    - pandas
    - pytz
    - requests
    - scikit-learn
    - scipy


test:
  imports:
    - ioos_tools

about:
  home: https://github.com/pyoceans/ioos_tools
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for IOOS notebooks'

extra:
  recipe-maintainers:
    - ocefpaf
