travis:
  secure:
    BINSTAR_TOKEN: ZACFgnKNSHat+v6fxGMOLaisIBskFHHiw6G/Ojwlvl5zygIamqjCPYYhss+NIJGzjXqUnv+BVvUANfcEbu05SUueHiQIUBzMpUsqwAadDdk0/8rnwuemfaR5WPx5LItfeEQrJh3e3wjStGM0FiE8UlxSMADN1ZvxxdqkRhRvGVGDEXvBgaH/xna+q6Wz6B1RaLdcH5pFhoi9N2S3vp3c/M9iHCbE5vPVsWoNDhX4gQNjZzGdPpDczyNxIiipx03+Yj7mHwA7nr78obG4/Y4fTdB5h5BY4Iy24giBKPFlAj2SBAxrOg8MZe1DOLe/aitm8hDMF9pHGissQriy+t3GPKEPd5OLvefKixCnsMsqVYozHfgyF6y5LvZ5fk9QHrPexfQmfKJLTPNMdQwgF9aO1XEbKTES0hIsP5IJc3DjK5RsXuTmMSjpDXc7WLKz0ziW/LmTV62Nqv3I5o98mgQbbfdNiNr57GZThM/HxfZbYwY5sK8ETPx6Mx6SSBtHBHODJfmeZ2md8rpSiR6CyQaX930AJ8d5/AoXzLJ21hSdEuuiFzk87Oxp+hT3KChZKtHrKEtXiAA3d9HKsfQe/Ca/Tzbo/Uc0h/ZKBJGKtB6cHB1zqB7m5URPSI1sqJq5FfxJ15EcpDg7+gXYvmLqtKi7DGizXCvM6E60si4i1jzsOjg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
